#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Multi-Arch Images

env:
  PREFIX_URL: https://downloads.immortalwrt.org/snapshots/targets

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      INPUT_TARGET:
        description: "Target to build (platform/target/subtarget)"
        required: false
        default: "all"
  schedule:
    - cron: 0 0 * * *

jobs:
  Config:
    name: Generate Config
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.find-targets.outputs.TARGETS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Targets
        id: find-targets
        env:
          INPUT_TARGET: ${{ github.event.inputs.INPUT_TARGET }}
        run: |
          if [ "$INPUT_TARGET" = "all" ] || [ "$INPUT_TARGET" = "" ]; then
            export TARGETS="$(cat config/platform.config)"
          else
            export TARGETS="$INPUT_TARGET"
          fi
          JSON='{"config": ["default"], "targets":['
          FIRST=1
          for TARGET in $TARGETS; do
          [[ $FIRST -ne 1 ]] && JSON="$JSON"','
          JSON="$JSON"'"'"${TARGET}"'"'
          FIRST=0
          done
          JSON="$JSON"']}'
          echo $JSON
          echo "::set-output name=TARGETS::$JSON"

  Docker-Images:
    name: ${{ matrix.TARGETS }}
    needs: [Config]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.Config.outputs.TARGETS)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 qemu-utils zstd

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Variables
        id: env
        run: |
          export DEVICE_PLATFORM=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $1}')
          echo "DEVICE_PLATFORM=$DEVICE_PLATFORM" >> $GITHUB_ENV
          export DEVICE_TARGET=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $2}')
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          export DEVICE_SUBTARGET=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $3}')
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          export DOCKER_IMAGE_ARCH=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $4}' | sed 's/-/\//g')
          echo "DOCKER_IMAGE_ARCH=$DOCKER_IMAGE_ARCH" >> $GITHUB_ENV
          export DOCKER_EXTERA_TAG=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $5}')
          echo "DOCKER_EXTERA_TAG=$DOCKER_EXTERA_TAG" >> $GITHUB_ENV
          export DEVICE_PROFILE=$(echo ${{ matrix.TARGETS }} | awk -F '/' '{print $6}')
          echo "DEVICE_PROFILE=$DEVICE_PROFILE" >> $GITHUB_ENV

          TAGS_MINI=""
          TAGS_NORMAL=""
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "HAS_DOCKERHUB=true" >> $GITHUB_ENV
            TAGS_MINI="${{ secrets.DOCKERHUB_USERNAME }}/openwrt-mini:$DEVICE_PLATFORM"
            TAGS_NORMAL="${{ secrets.DOCKERHUB_USERNAME }}/openwrt:$DEVICE_PLATFORM"
            if [ -n "$DOCKER_EXTERA_TAG" ]; then
              TAGS_MINI="$TAGS_MINI,${{ secrets.DOCKERHUB_USERNAME }}/openwrt-mini:$DOCKER_EXTERA_TAG"
              TAGS_NORMAL="$TAGS_NORMAL,${{ secrets.DOCKERHUB_USERNAME }}/openwrt:$DOCKER_EXTERA_TAG"
            fi
          else
            echo "HAS_DOCKERHUB=false" >> $GITHUB_ENV
          fi

          echo "TAGS_MINI=$TAGS_MINI" >> $GITHUB_ENV
          echo "TAGS_NORMAL=$TAGS_NORMAL" >> $GITHUB_ENV
          
          if [ -n "$TAGS_MINI" ]; then
            echo "SHOULD_PUSH=true" >> $GITHUB_ENV
          else
            echo "SHOULD_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Login To DockerHub
        if: env.HAS_DOCKERHUB == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Download Image Builder
        run: |
          wget $PREFIX_URL/$DEVICE_TARGET/$DEVICE_SUBTARGET/immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64.tar.zst
          ls -lh *.tar.zst

      - name: Set Mini Image Builder
        run: |
          tar -I zstd -xf *.tar.zst
          cd immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64
          cp -rf $GITHUB_WORKSPACE/files .
          chmod +x files/etc/rc.local

      - name: Build Mini RootFS
        run: |
          cd immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64
          sed -i "/CONFIG_TARGET_ROOTFS_SQUASHFS/s/.*/# CONFIG_TARGET_ROOTFS_SQUASHFS is not set/;
            /CONFIG_TARGET_ROOTFS_EXT4FS/s/.*/# CONFIG_TARGET_ROOTFS_EXT4FS is not set/" .config
          echo "CONFIG_TARGET_ROOTFS_TARGZ=y" >> .config
          export CONFIG_MINI_PACKAGES=$(cat $GITHUB_WORKSPACE/config/mini-packages.config | tr -s "\n" " ")
          if [ -n "$DEVICE_PROFILE" ]; then
            make image PROFILE="$DEVICE_PROFILE" PACKAGES="$CONFIG_MINI_PACKAGES" FILES="files"
          else
            make image PACKAGES="$CONFIG_MINI_PACKAGES" FILES="files"
          fi
          cp bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET/*rootfs.tar.gz $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          rm -rf immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64

      - name: Build & Push Mini Image
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKER_IMAGE_ARCH }}
          file: Dockerfile
          context: .
          push: ${{ env.SHOULD_PUSH }}
          tags: ${{ env.TAGS_MINI }}

      - name: Set Normal Image Builder
        run: |
          tar -I zstd -xf *.tar.zst
          cd immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64
          cp -rf $GITHUB_WORKSPACE/files .
          chmod +x files/etc/rc.local

      - name: Build Normal RootFS
        run: |
          cd immortalwrt-imagebuilder-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64
          chmod +x $GITHUB_WORKSPACE/scripts/*
          $GITHUB_WORKSPACE/scripts/preset-terminal-tools.sh
          sed -i "/CONFIG_TARGET_ROOTFS_SQUASHFS/s/.*/# CONFIG_TARGET_ROOTFS_SQUASHFS is not set/;
            /CONFIG_TARGET_ROOTFS_EXT4FS/s/.*/# CONFIG_TARGET_ROOTFS_EXT4FS is not set/" .config
          echo "CONFIG_TARGET_ROOTFS_TARGZ=y" >> .config
          export CONFIG_NORMAL_PACKAGES=$(cat $GITHUB_WORKSPACE/config/normal-packages.config | tr -s "\n" " ")
          if [ -n "$DEVICE_PROFILE" ]; then
            make image PROFILE="$DEVICE_PROFILE" PACKAGES="$CONFIG_NORMAL_PACKAGES" FILES="files"
          else
            make image PACKAGES="$CONFIG_NORMAL_PACKAGES" FILES="files"
          fi
          cp bin/targets/$DEVICE_TARGET/$DEVICE_SUBTARGET/*rootfs.tar.gz $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          rm -rf immortalwrt-imagebuilder*

      - name: Build & Push Normal Image
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKER_IMAGE_ARCH }}
          file: Dockerfile
          context: .
          push: ${{ env.SHOULD_PUSH }}
          tags: ${{ env.TAGS_NORMAL }}

  Update-Readme:
    name: Update DockerHub README
    runs-on: ubuntu-latest
    needs: [Docker-Images]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update DockerHub Description (Normal)
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PWD != ''
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/openwrt
          readme-filepath: ./README.md

      - name: Update DockerHub Description (Mini)
        if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_PWD != ''
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/openwrt-mini
          readme-filepath: ./README.md
